import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import Footer from "./../components/Footer";
import axios from "axios";

export default function Home() {
  const [email, setEmail] = useState("");

  const handleChange = (e) => {
    setEmail(e.target.value);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log(email);
    try {
      const response = await axios.post("http://localhost:4000/", {
        email,
      });
      setEmail("");
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className={styles.wrapper}>
      <Head>
        <title>METIME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/BoahmedAlHarf-Bold.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="true"
        />
      </Head>
      <div className={styles.container}>
        <Navbar />
        <main className={styles.hero}>
          <dev className={styles.desc}>
            <h2>Bientôt à votre service</h2>
            <h2>MeTime parce que votre temps est précieux !</h2>
            <h2 className={styles.arTitle}>
              مع <span>MeTime</span> وقتك بين يديك
            </h2>
            <p>
              Metime la première application pour prendre votre rendez-vous chez
              le coiffeur, hammam ou spa de votre choix
              <br />
              Soyez les premiers à vous inscrire et profitez de nos offres
              irrésistibles !!
            </p>
            <div className={styles.form}>
              <h3>Inscrivez-vous pour être averti lors de notre lancement</h3>
              <form onSubmit={handleSubmit}>
                <input
                  type="email"
                  placeholder="Entrez votre email ici"
                  onChange={handleChange}
                  value={email}
                />
                <p>Ne vous inquiétez pas, nous détestons aussi le spam</p>
              </form>
            </div>
          </dev>
          <dev className={styles.img}>
            <img src="/iphone.png" />
          </dev>
        </main>
        <Footer />
      </div>
    </div>
  );
}
